### ISSUE TITLE
Use of variables in coursework

### ISSUE THREAD

**Issue by laMudri** [fredrikNordvallForsberg/CS410-20#2]
In section [LET'S BE LOGICAL](https://github.com/fredrikNordvallForsberg/CS410-20/blob/master/Coursework/One.agda#L149), variables `P Q R : Set` are declared. Most definitions following then rely on this variable declaration, but some do not, and instead explicitly bind some of `P`, `Q`, and `R` (specifically: `orAdjunctionTo`, `¬¬deMorgan¬×`, `return`, `_>>=_`, and `¬¬-map`). Is this variation intended? It doesn't make any difference to the typed terms, but the change in style might be slightly confusing.

**Comment by fredrikNordvallForsberg** [comment]
Well spotted! It's a mixture of intention and oversight: `orAdjunctionTo` and `¬¬deMorgan¬×` would have made sense for them to use the variables, but for the monad structure I think it makes sense to keep things nice and local. Similarly `¬¬LEM` it makes sense to use `X` rather than a variable `P` for comparison with the universally quantified `X` in `Peirce→LEM` and `LEM→Peirce`.

I don't think it is a good idea to fix this now, as it could lead to merge conflicts, so I think we just have to live with the confusion.
